apiVersion: v1
kind: Service
metadata:
  name: weatherops-service
  namespace: weatherops
  labels:
    app: weatherops-dashboard
spec:
  type: ClusterIP
  selector:
    app: weatherops-dashboard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000